import { useMemo, useState } from "react";
import { motion } from "framer-motion";
import { Clock3, Filter, Search, Stethoscope, UsersRound } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useAppData } from "@/context/AppDataContext";
import { useAuth } from "@/context/AuthContext";
import { SPECIALTIES } from "@/lib/mockData";
import type { AppointmentStatus, Priority } from "@/lib/types";

const priority: Record<Priority, { label: string; order: number; cls: string }> = { emergencia: { label: "Emergência", order: 0, cls: "bg-red-100 text-red-700" }, alta: { label: "Alta", order: 1, cls: "bg-orange-100 text-orange-700" }, media: { label: "Média", order: 2, cls: "bg-amber-100 text-amber-700" }, baixa: { label: "Baixa", order: 3, cls: "bg-emerald-100 text-emerald-700" } };
const filters: { label: string; value: "todos" | "aguardando" | AppointmentStatus }[] = [{ label: "Todos", value: "todos" }, { label: "Aguardando", value: "aguardando" }, { label: "Em atendimento", value: "em_andamento" }, { label: "Concluídos", value: "concluida" }];

export default function ProfessionalQueue() {
  const { appointments } = useAppData(); const { professional } = useAuth(); const navigate = useNavigate(); const [filter, setFilter] = useState<string>("todos"); const [search, setSearch] = useState("");
  const items = useMemo(() => appointments.filter((apt) => apt.doctorId === professional?.id && apt.status !== "cancelada" && (filter === "todos" || (filter === "aguardando" ? ["agendada", "confirmada"].includes(apt.status) : apt.status === filter)) && `${apt.patientName} ${apt.reason}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => (priority[a.priority ?? "baixa"].order - priority[b.priority ?? "baixa"].order) || `${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`)), [appointments, professional, filter, search]);
  return <div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-secondary-foreground">Visão geral</p><h1 className="text-3xl font-extrabold text-primary">Fila de atendimento</h1><p className="mt-1 text-sm text-muted-foreground">Casos priorizados pela pré-triagem para uma decisão mais rápida.</p></div><div className="rounded-2xl border bg-white px-5 py-3"><span className="text-2xl font-extrabold text-primary">{items.filter((i) => i.status !== "concluida").length}</span><span className="ml-2 text-sm text-muted-foreground">casos ativos</span></div></div>
    <div className="mt-7 rounded-2xl border bg-white p-3"><div className="flex flex-col gap-3 xl:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input className="pl-9" placeholder="Buscar paciente ou motivo..." value={search} onChange={(e) => setSearch(e.target.value)} /></div><div className="flex gap-2 overflow-x-auto"><Filter className="m-2 h-4 w-4 text-muted-foreground"/>{filters.map((item) => <Button key={item.value} size="sm" variant={filter === item.value ? "default" : "ghost"} onClick={() => setFilter(item.value)}>{item.label}</Button>)}</div></div></div>
    <div className="mt-5 space-y-3">{items.length === 0 && <div className="rounded-3xl border border-dashed bg-white p-14 text-center"><UsersRound className="mx-auto h-10 w-10 text-secondary"/><h2 className="mt-3 font-bold">Nenhum paciente nesta fila</h2><p className="text-sm text-muted-foreground">Novos agendamentos compatíveis aparecerão automaticamente aqui.</p></div>}{items.map((apt, index) => { const p = priority[apt.priority ?? "baixa"]; const spec = SPECIALTIES.find((s) => s.id === apt.specialtyId); return <motion.button initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .03 }} key={apt.id} onClick={() => navigate(`/profissional/atendimento/${apt.id}`)} className="grid w-full gap-4 rounded-2xl border bg-white p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-secondary hover:shadow-md md:grid-cols-[1.4fr_1fr_auto] md:items-center"><div className="flex items-center gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-accent font-bold text-primary">{(apt.patientName ?? "Carlos Silva").split(" ").map((n) => n[0]).slice(0,2).join("")}</div><div><div className="flex flex-wrap items-center gap-2"><p className="font-bold">{apt.patientName ?? "Carlos Silva"}</p><Badge className={p.cls}>{p.label}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{apt.reason}</p></div></div><div className="space-y-1 text-sm text-slate-600"><p className="flex items-center gap-2"><Stethoscope className="h-4 w-4"/>{spec?.name}</p><p className="flex items-center gap-2"><Clock3 className="h-4 w-4"/>{new Date(`${apt.date}T12:00:00`).toLocaleDateString("pt-BR")} · {apt.time}</p></div><Badge variant="outline" className="justify-self-start md:justify-self-end">{apt.status === "em_andamento" ? "Em atendimento" : apt.status === "concluida" ? "Concluído" : "Aguardando"}</Badge></motion.button>; })}</div>
  </div>;
}
