import { Award, LogOut, Mail, ShieldCheck, Stethoscope } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/context/AuthContext";
import { SPECIALTIES } from "@/lib/mockData";

export default function ProfessionalProfile() {
  const { professional, professionalLogout } = useAuth(); const navigate = useNavigate(); const specialty = SPECIALTIES.find((s) => s.id === professional?.specialtyId);
  return <div className="mx-auto max-w-3xl"><h1 className="text-3xl font-extrabold text-primary">Perfil profissional</h1><div className="mt-7 overflow-hidden rounded-3xl border bg-white"><div className="h-28 bg-primary"/><div className="px-6 pb-7"><div className="-mt-12 flex h-24 w-24 items-center justify-center rounded-3xl border-4 border-white bg-secondary text-2xl font-extrabold text-primary">{professional?.initials}</div><h2 className="mt-4 text-2xl font-extrabold">{professional?.name}</h2><p className="text-muted-foreground">{professional?.crm}</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><div className="flex items-center gap-3 rounded-2xl bg-muted/60 p-4"><Stethoscope className="text-primary"/><div><p className="text-xs text-muted-foreground">Especialidade</p><p className="font-bold">{specialty?.name}</p></div></div><div className="flex items-center gap-3 rounded-2xl bg-muted/60 p-4"><Award className="text-primary"/><div><p className="text-xs text-muted-foreground">Avaliação</p><p className="font-bold">{professional?.rating} de 5</p></div></div><div className="flex items-center gap-3 rounded-2xl bg-muted/60 p-4"><Mail className="text-primary"/><div><p className="text-xs text-muted-foreground">E-mail</p><p className="font-bold">mariana@vita.med.br</p></div></div><div className="flex items-center gap-3 rounded-2xl bg-emerald-50 p-4"><ShieldCheck className="text-emerald-700"/><div><p className="text-xs text-emerald-700">Acesso</p><p className="font-bold text-emerald-900">Profissional autorizado</p></div></div></div><Button variant="outline" className="mt-7 text-destructive" onClick={() => { professionalLogout(); navigate("/profissional/login"); }}><LogOut/>Sair da conta</Button></div></div></div>;
}
