import { useEffect, useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { AlertTriangle, ArrowLeft, CheckCircle2, FileText, FlaskConical, HeartPulse, Paperclip, Pill, Plus, Save, Send, Stethoscope, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useAppData } from "@/context/AppDataContext";
import { useAuth } from "@/context/AuthContext";
import { SPECIALTIES } from "@/lib/mockData";
import type { CareDraft, Priority } from "@/lib/types";

const pLabels: Record<Priority, string> = { emergencia: "Emergência", alta: "Alta", media: "Média", baixa: "Baixa" };
const profile = { medications: ["Losartana 50 mg — uso contínuo"], allergies: ["Dipirona"], chronicConditions: ["Hipertensão arterial"] };
const empty: CareDraft = { clinicalNotes: "", diagnosis: "", recommendations: "", prescriptions: [], examRequests: [], referral: "", needsReturn: false };

function ListEditor({ values, onChange, placeholder, icon: Icon }: { values: string[]; onChange: (v: string[]) => void; placeholder: string; icon: typeof Pill }) {
  const [value, setValue] = useState("");
  return <div><div className="flex gap-2"><Input value={value} onChange={(e) => setValue(e.target.value)} placeholder={placeholder} onKeyDown={(e) => { if (e.key === "Enter") { e.preventDefault(); if (value.trim()) { onChange([...values, value.trim()]); setValue(""); } } }} /><Button type="button" variant="outline" onClick={() => { if (value.trim()) { onChange([...values, value.trim()]); setValue(""); } }}><Plus className="h-4 w-4"/>Adicionar</Button></div><div className="mt-2 space-y-2">{values.map((item, i) => <div key={`${item}-${i}`} className="flex items-center gap-2 rounded-xl bg-muted/60 px-3 py-2 text-sm"><Icon className="h-4 w-4 text-primary"/><span className="flex-1">{item}</span><button onClick={() => onChange(values.filter((_, x) => x !== i))}><Trash2 className="h-4 w-4 text-muted-foreground"/></button></div>)}</div></div>;
}

export default function ProfessionalCare() {
  const { id } = useParams(); const navigate = useNavigate(); const { professional } = useAuth();
  const { appointments, triageResults, medicalRecords, startAppointment, saveCare, concludeCare } = useAppData();
  const apt = appointments.find((item) => item.id === id); const triage = triageResults.find((item) => item.id === apt?.triageId); const existing = medicalRecords.find((item) => item.appointmentId === id);
  const [draft, setDraft] = useState<CareDraft>(empty); const [confirmOpen, setConfirmOpen] = useState(false); const [loading, setLoading] = useState(true);
  useEffect(() => { const timer = setTimeout(() => setLoading(false), 550); return () => clearTimeout(timer); }, []);
  useEffect(() => { if (existing) setDraft({ clinicalNotes: existing.clinicalNotes ?? "", diagnosis: existing.diagnosis, recommendations: existing.recommendations, prescriptions: existing.prescriptions, examRequests: existing.examRequests ?? [], referral: existing.referral ?? "", needsReturn: existing.needsReturn ?? false, returnDate: existing.returnDate }); else if (triage) setDraft((d) => ({ ...d, diagnosis: triage.hypothesis })); }, [existing, triage]);
  const specialty = SPECIALTIES.find((s) => s.id === apt?.specialtyId); const summary = useMemo(() => Object.entries(triage?.summary ?? {}), [triage]);
  const patientRecords = medicalRecords.filter((record) => !record.patientId || !apt?.patientId || record.patientId === apt.patientId);
  if (!apt) return <div className="rounded-2xl border bg-white p-10 text-center"><p className="font-bold">Atendimento não encontrado.</p><Button className="mt-4" onClick={() => navigate("/profissional/fila")}>Voltar à fila</Button></div>;
  if (loading) return <div className="space-y-4"><div className="h-24 animate-pulse rounded-2xl bg-white"/><div className="h-96 animate-pulse rounded-2xl bg-white"/></div>;
  const set = <K extends keyof CareDraft>(key: K, value: CareDraft[K]) => setDraft((current) => ({ ...current, [key]: value }));
  const save = () => { saveCare(apt.id, draft, professional!.name); toast.success("Registro clínico salvo com data e responsável."); };
  const finish = () => { if (!draft.clinicalNotes.trim() || !draft.diagnosis.trim() || !draft.recommendations.trim()) { toast.error("Preencha observações, hipótese e orientações antes de concluir."); return; } setConfirmOpen(true); };
  const conclude = () => { concludeCare(apt.id, draft, professional!.name); setConfirmOpen(false); toast.success("Atendimento concluído e prontuário atualizado."); navigate("/profissional/fila"); };
  return <div className="mx-auto max-w-7xl"><button onClick={() => navigate("/profissional/fila")} className="mb-4 flex items-center gap-2 text-sm font-semibold text-primary"><ArrowLeft className="h-4 w-4"/>Voltar à fila</button>
    <div className="flex flex-col justify-between gap-4 rounded-2xl bg-primary p-5 text-white md:flex-row md:items-center"><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-extrabold">{apt.patientName ?? "Carlos Silva"}</h1><Badge className="bg-white/15 text-white">Prioridade {pLabels[apt.priority ?? "baixa"]}</Badge></div><p className="mt-1 text-sm text-white/70">{specialty?.name} · {apt.modality === "teleconsulta" ? "Teleconsulta" : "Presencial"} · {apt.time}</p></div><div className="flex gap-2">{apt.status !== "em_andamento" && apt.status !== "concluida" && <Button variant="secondary" onClick={() => { startAppointment(apt.id, professional!.name); toast.success("Atendimento iniciado. O paciente foi notificado."); }}>Iniciar atendimento</Button>}<Button className="bg-white text-primary hover:bg-white/90" onClick={save}><Save/>Salvar</Button></div></div>
    <Tabs defaultValue="relatorio" className="mt-5"><TabsList className="h-auto w-full justify-start overflow-x-auto bg-white p-1"><TabsTrigger value="relatorio">Relatório de pré-triagem</TabsTrigger><TabsTrigger value="conduta">Condução do atendimento</TabsTrigger><TabsTrigger value="prontuario">Resumo do prontuário</TabsTrigger></TabsList>
      <TabsContent value="relatorio" className="mt-5 grid gap-5 lg:grid-cols-[1.5fr_1fr]"><div className="space-y-5"><Card><CardHeader><CardTitle className="flex items-center gap-2"><FileText className="text-primary"/>Queixa e análise inicial</CardTitle></CardHeader><CardContent className="space-y-4"><div><p className="text-xs font-bold uppercase text-muted-foreground">Sintoma principal</p><p className="mt-1 text-lg font-semibold">{triage?.chiefComplaint ?? apt.reason}</p></div><div className="rounded-xl bg-accent p-4"><p className="text-xs font-bold uppercase text-primary">Hipótese gerada pela triagem</p><p className="mt-1 text-sm">{triage?.hypothesis ?? "Sem hipótese automatizada vinculada."}</p></div>{summary.length > 0 && <div className="grid gap-3 sm:grid-cols-2">{summary.map(([key, value]) => <div key={key} className="rounded-xl border p-3"><p className="text-xs font-bold capitalize text-muted-foreground">{key}</p><p className="mt-1 text-sm">{value}</p></div>)}</div>}<div className="rounded-xl border border-dashed p-4"><p className="flex items-center gap-2 font-semibold"><Paperclip className="h-4 w-4"/>Anexos do paciente</p><p className="mt-1 text-sm text-muted-foreground">Nenhum documento anexado nesta triagem.</p></div></CardContent></Card></div>
        <div className="space-y-4"><Card className="border-orange-200"><CardHeader><CardTitle className="flex items-center gap-2 text-orange-800"><AlertTriangle/>Alertas de segurança</CardTitle></CardHeader><CardContent className="space-y-3"><div><p className="text-xs font-bold text-muted-foreground">ALERGIA</p><p className="font-semibold text-red-700">{profile.allergies.join(", ")}</p></div><div><p className="text-xs font-bold text-muted-foreground">CONDIÇÃO CRÔNICA</p><p className="font-semibold">{profile.chronicConditions.join(", ")}</p></div><div><p className="text-xs font-bold text-muted-foreground">MEDICAÇÃO EM USO</p><p className="font-semibold">{profile.medications.join(", ")}</p></div></CardContent></Card><Button className="w-full" onClick={() => (document.querySelector('[data-value="conduta"]') as HTMLElement)?.click()}>Ir para condução <Stethoscope/></Button></div></TabsContent>
      <TabsContent value="conduta" className="mt-5"><div className="grid gap-5 xl:grid-cols-2"><Card><CardHeader><CardTitle>Avaliação clínica</CardTitle></CardHeader><CardContent className="space-y-4"><div className="space-y-1.5"><Label>Observações clínicas *</Label><Textarea rows={6} value={draft.clinicalNotes} onChange={(e) => set("clinicalNotes", e.target.value)} placeholder="Anamnese, sinais observados e evolução..."/></div><div className="space-y-1.5"><Label>Hipótese diagnóstica *</Label><Input value={draft.diagnosis} onChange={(e) => set("diagnosis", e.target.value)} /></div><div className="space-y-1.5"><Label>Orientações ao paciente *</Label><Textarea rows={4} value={draft.recommendations} onChange={(e) => set("recommendations", e.target.value)} placeholder="Cuidados, sinais de alerta e próximos passos..."/></div></CardContent></Card>
        <div className="space-y-5"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Pill className="text-primary"/>Prescrição</CardTitle></CardHeader><CardContent><ListEditor values={draft.prescriptions} onChange={(v) => set("prescriptions", v)} placeholder="Medicamento, dose e posologia" icon={Pill}/></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><FlaskConical className="text-primary"/>Exames complementares</CardTitle></CardHeader><CardContent><ListEditor values={draft.examRequests} onChange={(v) => set("examRequests", v)} placeholder="Nome do exame solicitado" icon={FlaskConical}/></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><Send className="text-primary"/>Encaminhamento e retorno</CardTitle></CardHeader><CardContent className="space-y-4"><div><Label>Encaminhar para especialidade</Label><Input className="mt-1.5" value={draft.referral} onChange={(e) => set("referral", e.target.value)} placeholder="Opcional"/></div><label className="flex items-center gap-3 rounded-xl bg-muted/60 p-3 text-sm font-semibold"><input type="checkbox" checked={draft.needsReturn} onChange={(e) => set("needsReturn", e.target.checked)}/>Paciente necessita de retorno</label>{draft.needsReturn && <Input type="date" value={draft.returnDate ?? ""} onChange={(e) => set("returnDate", e.target.value)}/>}</CardContent></Card></div></div><div className="mt-5 flex flex-wrap justify-end gap-3"><Button variant="outline" onClick={save}><Save/>Salvar rascunho</Button><Button onClick={finish} disabled={apt.status === "concluida"}><CheckCircle2/>Concluir atendimento</Button></div></TabsContent>
      <TabsContent value="prontuario" className="mt-5"><Card><CardHeader><CardTitle className="flex items-center gap-2"><HeartPulse className="text-primary"/>Histórico clínico</CardTitle></CardHeader><CardContent>{patientRecords.length === 0 ? <p className="rounded-xl border border-dashed p-8 text-center text-sm text-muted-foreground">Paciente sem histórico clínico anterior.</p> : <div className="space-y-4">{patientRecords.map((record) => <div key={record.id} className="border-l-2 border-secondary pl-4"><p className="text-xs text-muted-foreground">{new Date(record.date).toLocaleDateString("pt-BR")} · {record.doctorName}</p><p className="mt-1 font-bold">{record.diagnosis}</p><p className="text-sm text-muted-foreground">{record.recommendations}</p></div>)}</div>}</CardContent></Card></TabsContent>
    </Tabs>
    <Dialog open={confirmOpen} onOpenChange={setConfirmOpen}><DialogContent><DialogHeader><DialogTitle>Concluir este atendimento?</DialogTitle><DialogDescription>O status será atualizado, o registro ficará disponível no prontuário e o paciente receberá uma notificação.</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={() => setConfirmOpen(false)}>Revisar</Button><Button onClick={conclude}>Confirmar conclusão</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
