import { useState } from "react";
import { AlertCircle, ChevronRight, FileHeart, Search } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { useAppData } from "@/context/AppDataContext";
import { SPECIALTIES } from "@/lib/mockData";

export default function ProfessionalRecords() {
  const { medicalRecords } = useAppData(); const [search, setSearch] = useState("");
  const records = medicalRecords.filter((r) => `${r.patientName} ${r.diagnosis}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="mx-auto max-w-6xl"><h1 className="text-3xl font-extrabold text-primary">Prontuários</h1><p className="mt-1 text-sm text-muted-foreground">Histórico, evolução, prescrições, exames e retornos dos pacientes.</p><div className="relative mt-6 max-w-xl"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input className="bg-white pl-9" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Buscar paciente ou diagnóstico..."/></div><div className="mt-5 grid gap-4 lg:grid-cols-2">{records.map((r) => <article key={r.id} className="rounded-2xl border bg-white p-5"><div className="flex items-start gap-3"><div className="rounded-xl bg-accent p-2 text-primary"><FileHeart/></div><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold">{r.patientName ?? "Carlos Silva"}</h2>{r.needsReturn && <Badge className="bg-amber-100 text-amber-800"><AlertCircle/>Retorno pendente</Badge>}</div><p className="text-xs text-muted-foreground">{new Date(r.date).toLocaleDateString("pt-BR")} · {SPECIALTIES.find((s) => s.id === r.specialtyId)?.name}</p></div><ChevronRight className="text-muted-foreground"/></div><div className="mt-4 rounded-xl bg-muted/50 p-3"><p className="text-xs font-bold uppercase text-muted-foreground">Evolução / diagnóstico</p><p className="mt-1 text-sm font-semibold">{r.diagnosis}</p><p className="mt-1 text-sm text-muted-foreground">{r.clinicalNotes || r.recommendations}</p></div><div className="mt-3 flex flex-wrap gap-2 text-xs"><Badge variant="outline">{r.prescriptions.length} prescrições</Badge><Badge variant="outline">{r.examResults?.length ?? 0} exames</Badge>{r.updatedBy && <span className="ml-auto text-muted-foreground">Atualizado por {r.updatedBy}</span>}</div></article>)}{records.length === 0 && <div className="col-span-full rounded-2xl border border-dashed bg-white p-12 text-center"><FileHeart className="mx-auto text-secondary"/><p className="mt-3 font-bold">Nenhum prontuário encontrado</p><p className="text-sm text-muted-foreground">Registros aparecem após o primeiro atendimento concluído.</p></div>}</div></div>;
}
